### ISSUE TITLE
Please Review

### ISSUE THREAD

**Issue by hamelsmu** [fastai/docker-containers#2]
@muellerzr / @jph00 can you please review this README and let me know if you have any thoughts or comments?  

@giacomov please take a look and let me know your thoughts.  Many thanks for your prior art which I built on top of.  I put a note with a link to your name in the README.

**Comment by hamelsmu** [comment]
Note that Docker Images are built daily.  We can also manually trigger a build to happen any time through this menu:

![image](https://user-images.githubusercontent.com/1483922/89093582-a10cf400-d370-11ea-8aad-ad8ab9efeec7.png)

**Comment by giacomov** [comment]
Thanks, looks great!

I don't think the --allow-root option is necessary for Jupiter or the shell. Since we create a user in the Dockerfile and we set it as the USER, Jupiter will run as that user inside the container. It is a bit of a security risk because if somebody gets access to that Jupiter they could potentially become root and write with root privileges on some mounted volumes from the host.

**Comment by hamelsmu** [comment]
I want to show folks how to switch to root if they want to for example if you want to install something or you are using the container for development purposes and not shipping it into a product.  But the container doesn’t run as root by default.

**Comment by hamelsmu** [comment]
Oh I see what you mean now I think too many examples have root in them by accident!  I’ll change this now

**Comment by giacomov** [comment]
awesome, looks perfect now.

**Comment by jph00** [comment]
Looking good. I'd remove the `details` tag and leave that whole section as a standard part of the readme. If you really think some of it needs to be collapsed, I'd suggest ensuring there's an introductory sentence e.g. "most people don't need to know <x>, but if you do, for instance because <y>, click below to view the details".

Also, please add a paragraph at the top saying that fast.ai recommends using anaconda in your home directory, and installing fastai directly into there, if possible - the docker containers are for those that need them for production, testing, online services, and so forth (or for those who can't use anaconda for some reason).
